luac -l -p $* \
| grep '[GS]ETGLOBAL' \
| grep -v '; ww_' \
| grep -v '; WeightsWatcher' \
| grep -v '; i\?pairs$' \
| grep -v '; string$' \
| grep -v '; print$' \
| grep -v '; type$' \
| grep -v '; table$' \
| grep -v '; [gs]etmetatable$' \
| grep -v '; CURRENTLY_EQUIPPED$' \
| grep -v '; rawget$' \
| grep -v '; GetInventoryItemLink$' \
| grep -v '; GetNumTalents$' \
| grep -v '; math$' \
| grep -v '; GetTalentInfo$' \
| grep -v '; unpack$' \
| grep -v '; AtlasLootTooltip$' \
| grep -v '; GetItemInfo$' \
| grep -v '; GetNumTalentTabs$' \
| grep -v '; IsEquippableItem$' \
| grep -v '; DisableAddOn$' \
| grep -v '; StaticPopup_Show$' \
| grep -v '; UnitLevel$' \
| grep -v '; ReloadUI$' \
| grep -v '; _G$' \
| grep -v '; SlashCmdList$' \
| grep -v '; StaticPopupDialogs$' \
| grep -v '; strsplit$' \
| grep -v '; strjoin$' \
| grep -v '; UnitClass$' \
| grep -v '; GetInventorySlotInfo$' \
| grep -v '; SLASH_WEIGHTSWATCHER[0-9]\+$' \
| grep -v '; GetLocale$' \
| grep -v '; tonumber$' \
| grep -v '; tostring$' \
| grep -v '; UIDropDownMenu_\(AddButton\|SetSelectedValue\)$' \
| grep -v '; AceLibrary$' \
| grep -v '; CreateFrame$' \
| grep -v '; select$' \
| grep -v '; io$' \
| grep -v '; load\(file\|string\)$' \
| grep -v '; pcall$' \
| grep -v '; debug$' \
| grep -v '; error$' \
| grep -v '; Is\([A-Z][a-z]\+\)\+KeyDown$' \
| grep -v '; FauxScrollFrame_\([GS]etOffset\|Update\)$' \
| grep -v '; GetPrimaryTalentTree$' \
| grep -v sort
